version: '3'

services:
  payment:
    image: payment:latest
    ports:  
      - 50051:50051

  front-end:
    image: front-end:latest
    ports:
      - 4200:80
    links:
    # depends_on: 
      - customer
      - catalog
      - order
  customer:
    image: customer:latest
    environment:
      - "ELASTIC_APM_SERVICE_NAME=Customer-service"
      - "ELASTIC_APM_APPLICATION_PACKAGES=com.ewolff.microservice.customer.web"
      - "ELASTIC_APM_SERVER_URLS=http://elastic-apm-elk-dv.apps.dev.ose.keybank.com:80"
    # ports:
    #   - 4201:8080
    links:
      - db
  catalog:
    image: catalog:latest
    environment:
      - "ELASTIC_APM_SERVICE_NAME=Catalog-service"
      - "ELASTIC_APM_APPLICATION_PACKAGES=com.ewolff.microservice.catalog.web"
      - "ELASTIC_APM_SERVER_URLS=http://elastic-apm-elk-dv.apps.dev.ose.keybank.com:80"
    links:
      - db
  order:
    image: order:latest
    environment:
      - "ELASTIC_APM_SERVICE_NAME=Order-service"
      - "ELASTIC_APM_APPLICATION_PACKAGES=com.ewolff.microservice.order.logic"
      - "ELASTIC_APM_SERVER_URLS=http://elastic-apm-elk-dv.apps.dev.ose.keybank.com:80"
      - "PAYMENT_SERVICE_URL=http://localhost:50051"
    links:
      - db



  db:
    image: mongo:3.4.4
    volumes:
      - ./$PWD/data/db:/Users/shanmel/data/db/
    ports:
      - "27017:27017" 